# For more information: https://laravel.com/docs/sail
version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - sail
        depends_on:
            - mysql
            - redis-master

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - sail

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    fix-redis-volume-ownership: # This service is to authorise redis-master with ownership permissions
        image: 'bitnami/redis:latest'
        user: root
        command: chown -R 1001:1001 /bitnami
        volumes:
            - ./data/redis:/bitnami
            - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf

    redis-master: # Setting up master node
        image: 'bitnami/redis:latest'
        ports:
            - '6329:6379' # Port 6329 will be exposed to handle connections from outside server
        environment:
            - REDIS_REPLICATION_MODE=master # Assigning the node as a master
            - ALLOW_EMPTY_PASSWORD=yes # No password authentication required/ provide password if needed
        volumes:
            - ./data/redis:/bitnami # Redis master data volume
            - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf # Redis master configuration volume

    redis-replica: # Setting up slave node
        image: 'bitnami/redis:latest'
        ports:
            - '6379' # No port is exposed
        depends_on:
            - redis-master # will only start after the master has booted completely
        environment:
            - REDIS_REPLICATION_MODE=slave # Assigning the node as slave
            - REDIS_MASTER_HOST=redis-master # Host for the slave node is the redis-master node
            - REDIS_MASTER_PORT_NUMBER=6379 # Port number for local
            - ALLOW_EMPTY_PASSWORD=yes # No password required to connect to node

    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.14.0'
        ports:
            - '9200:9200'
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
